import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "IMDb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="Ja">
      <body>
        <Header />
        {/* Navber */}
        {/* SearchBox */}
        {children}
      </body>
    </html>
  );
}
